function rhs2hat = R2ts(p,psihmat,dpsihmat,omzhmat,domzhmat)

gm = p.con.gm;

Kx = p.smesh.Kx;
Ky = p.smesh.Ky;
frgamma = p.sim.frgamma;
frgamma = 1;
% psihmat = fft2(psimat);
% dpsihmat = fft2(dpsimat);

unfiltered = - ifft2(1i*Ky.*psihmat) .* ifft2(-1i*(Kx.^3).*dpsihmat) ...
            -  ifft2(1i*Ky.*psihmat) .* ifft2(-1i*(Kx.*Ky.^2).*dpsihmat) ...
            +  ifft2(1i*Kx.*psihmat) .* ifft2(-1i*(Ky.*Kx.^2).*dpsihmat) ...
            +  ifft2(1i*Kx.*psihmat) .* ifft2(-1i*(Ky.^3).*dpsihmat) ...
            -  ifft2(1i*Ky.*dpsihmat) .* ifft2(-1i*(Kx.^3).*psihmat) ...
            -  ifft2(1i*Ky.*dpsihmat) .* ifft2(-1i*(Kx.*Ky.^2).*psihmat) ...
            +  ifft2(1i*Kx.*dpsihmat) .* ifft2(-1i*(Ky.*Kx.^2).*psihmat) ...
            +  ifft2(1i*Kx.*dpsihmat) .* ifft2(-1i*(Ky.^3).*psihmat);
filtered = imgaussfilt(real(unfiltered),frgamma, ...
                    'FilterDomain','spatial','Padding','circular');
rhs2hat = fft2(gm * filtered);
% rhs2hat = fft2(gm*unfiltered);
end