function [I, J, Ip1, Im1, Jp1, Jm1, Ip2, Im2, Jp2, Jm2] = unpackIndexStructPBC(p)
%UNWRAPINDEXPBC Unwraps periodic index arrays from p.idx struct
%
%   This function extracts the index arrays assuming they are stored in p.idx
%   and were generated by makeIndexStructPBC.

    I   = p.idx.I;
    J   = p.idx.J;

    Ip1 = p.idx.Ip1;
    Im1 = p.idx.Im1;
    Ip2 = p.idx.Ip2;
    Im2 = p.idx.Im2;

    Jp1 = p.idx.Jp1;
    Jm1 = p.idx.Jm1;
    Jp2 = p.idx.Jp2;
    Jm2 = p.idx.Jm2;
end